# Change these first
owner: ismanf # Your GitHub organization or username, where this repository lives
repo: uptime-test # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Youtube
    url: https://youtube.com
  - name: Yahoo
    url: https://yahoo.com

status-website:
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: My Upptime
  introTitle: "This is my test status page"
  introMessage: I dont like to add descriptions bla bla

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
